### ISSUE TITLE
[en-GB] Update the British dictionary for V3.2.7 — 2023-12-01

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/english-pos-dict#1]
Heya,

Could someone update the GB dictionary for LanguageTool's release at the end of the month?:
https://github.com/marcoagpinto/aoo-mozilla-en-dict

Thanks!

**Comment by AzadehSafakish** [comment]
Hello,
Update on where this is going:

The delay is because we're making the EN dictionary an external dependency, so all dictionary functions will be moved to [english-pos-dict](https://github.com/languagetool-org/english-pos-dict).
I am transferring your issue there.
We will not be updating the dictionary until the new setup is in place, but that is expected to complete in just a couple of days.
The dictionary will be updated by year-end, at the latest.
I would also like to inform you that we've changed the schedule for new releases; the next release will be [in March](https://dev.languagetool.org/roadmap.html), not at the end of December.

**Comment by jaumeortola** [comment]
When we do "unmunch" of the Hunspell GB files, we get some entries with tabs and comments. You can see them in this file: 
[en_GB-tabs.txt](https://github.com/languagetool-org/english-pos-dict/files/13808639/en_GB-tabs.txt)
Obviously, the tabs and the comments have to be removed.
Some entries are really for multiwords.txt (e.g., Anno Domini, Taj Mahal). Do we want the individual tokens in the spelling dict?
Apart from that, I think we don't need to tokenize the words from the Hunspell dicts. The words with `'s` can be included in the binary file. They can be good suggestions.
@AzadehSafakish

**Comment by marcoagpinto** [comment]
Heya,

The “unmunched” wordlist is already included in my GitHub repository, no need to unmunch it:
https://github.com/marcoagpinto/aoo-mozilla-en-dict/tree/master/en_GB%20(Marco%20Pinto)

[wordlist_marcoagpinto_20240101_275477w.txt](https://github.com/marcoagpinto/aoo-mozilla-en-dict/blob/master/en_GB%20(Marco%20Pinto)/wordlist_marcoagpinto_20240101_275477w.txt)

2024-01-01 released yesterday!

**Comment by AzadehSafakish** [comment]
>Do we want the individual tokens in the spelling dict?

I don't think it's a huge issue, but preferably not.
@jaumeortola Would it make sense for me to go through the list and add relevant entries to multiwords?
And report back the individual entries that I would remove?

>The words with 's can be included in the binary file. They can be good suggestions.

Perhaps not the most relevant suggestions, but I assume they'll be in a list with the more likely plural form (+`s`), so there's no harm in it.

**Comment by jaumeortola** [comment]
> Would it make sense for me to go through the list and add relevant entries to multiwords? And report back the individual entries that I would remove?

@AzadehSafakish Yes, it makes sense. 

> Perhaps not the most relevant suggestions, but I assume they'll be in a list with the more likely plural form (+s), so there's no harm in it.

I agree. There's no harm. Anyway, we will generate a diff to compare the results before and after the new binary dictionaries.

**Comment by AzadehSafakish** [comment]
Dictionary was updated when repackaged as an external dependency, thanks to @jaumeortola !
Closing.
