### ISSUE TITLE
Consolidate -ize/-ise words

### ISSUE THREAD

**Issue by AzadehSafakish** [languagetool-org/english-pos-dict#13]
**Description**

We need to clean up and consolidate -ize/-ise words across all English variants.
[clean-verbs-ise.txt](https://github.com/languagetool-org/english-pos-dict/files/15106660/clean-verbs-ise.txt)
[clean-verbs-ize.txt](https://github.com/languagetool-org/english-pos-dict/files/15106661/clean-verbs-ize.txt)
[pending-verbs-ise.txt](https://github.com/languagetool-org/english-pos-dict/files/15106665/pending-verbs-ise.txt)
[pending-verbs-ize.txt](https://github.com/languagetool-org/english-pos-dict/files/15106666/pending-verbs-ize.txt)

This entails the following tasks:

**DoD**
 - [x] Establish general criteria for determining a word's variant(s). [Wikipedia](https://en.wikipedia.org/wiki/Oxford_spelling#Language_tag_comparison) appears to be a good source.
 - [x] Using this criteria, verify that all words have the correct variant labels and correct them where necessary
 - [x] Once the correct variant labels are in place, ensure that all entries have a complete and accurate list of inflections. Edit/remove entries if required.

**Comment by jaumeortola** [comment]
https://github.com/languagetool-org/english-pos-dict/commit/d82596458b9b0a64d99874111833c6ef5e8c7c9c
