### ISSUE TITLE
Consolidate -isation / -ization words

### ISSUE THREAD

**Issue by jaumeortola** [languagetool-org/english-pos-dict#14]
All words with terminations -isation/-ization from the dictionaries. They are sorted alphabetically so that `absolutization` comes after `absolutisation`, and so on.
[isation.txt](https://github.com/languagetool-org/english-pos-dict/files/15109764/isation.txt)

- [x] Define shorthands for nouns (https://github.com/languagetool-org/english-pos-dict/issues/6)
- [x] Is the spelling -isation/-ization general for all words, without exceptions? If that is true, we could use this rule of thumb: `For words -ization/-isation, add the -s- form to the GB, AU, NZ and ZA dicts, and the -z- form to US, CA, and GB (because of the Oxford spelling).`
- [x] Is there a way to know if these nouns are `:U` or `:UN`?
- [x] Is there a way to know when a plural is required or not? Could we just create plural forms for all, even if they are unusual?

**Comment by AzadehSafakish** [comment]
>Is the spelling -isation/-ization general for all words, without exceptions? If that is true, we could use this rule of thumb: For words -ization/-isation, add the -s- form to the GB, AU, NZ and ZA dicts, and the -z- form to US, CA, and GB (because of the Oxford spelling).

This checks out ✅ 

> Is there a way to know if these nouns are :U or :UN?
Is there a way to know when a plural is required or not? Could we just create plural forms for all, even if they are unusual?

NN:UN, I would create a plural NNS even if it's unusual.

**Comment by jaumeortola** [comment]
Done here: https://github.com/languagetool-org/english-pos-dict/commit/ee2c3ba74746258e601668acdd7d420a2aad80d5

Entries revised and written in this way:
> Africanization|Africanisation=noun_UN=us,ca,gb|gb,au,nz,za

Removed some nonsense words: mostly untagged and from the GB speller dictionary. 

Observations:
- a few words with prefixes (anti-, pro-, inter-) are adjectives (JJ)
- there is some vacillation in the use of hyphens with prefixes (anti-, pre-, pro-, non-...): antimodernization / anti-modernization. I don't know if it can be uniformized. Should we always add both forms?

**Comment by AzadehSafakish** [comment]
>Should we always add both forms?

I don't think so. There are lots of rules with prefixes and hyphens, and usually it the correct spelling comes down to "use a hyphen if it looks weird not to." "Anti" especially tends not to be hyphenated in the realm of science/medicine, but can take a hyphen in other contexts. There isn't really a uniform rule, so I wouldn't add forms that aren't in the dictionary already. But I wonder if @evan-defran-lt has a different take.
