### ISSUE TITLE
Plurals of words -ness

### ISSUE THREAD

**Issue by jaumeortola** [languagetool-org/english-pos-dict#16]
The dictionary contains ~3500 words like this:
> acuteness=acuteness/NN:U,acutenesses/NNS=all

I guess the plural form `-nessess` is very infrequent. Is it okay to have the plurals in the dictionary? For all -ness words? 
Is this the desired tagging?

**Comment by AzadehSafakish** [comment]
>I guess the plural form -nessess is very infrequent. Is it okay to have the plurals in the dictionary? For all -ness words?

If they're tagged with `NN:U`, I would say no.
But, there might be some that actually are countable (like 'harness/harnesses'). I wouldn't remove the plural forms of countable nouns.

Do you have a list I can quickly review?

**Comment by jaumeortola** [comment]
There are the lists. One from "clean" (tagged and in all spelling dicts) and one from "pending". 
[ness-pending.txt](https://github.com/languagetool-org/english-pos-dict/files/15459354/ness-pending.txt)
[ness-clean.txt](https://github.com/languagetool-org/english-pos-dict/files/15459355/ness-clean.txt)

**Comment by jaumeortola** [comment]
Looking into a dictionary of frequencies, these are the only plurals in the first 400,000 word forms:

```
businesses
witnesses
illnesses
weaknesses
eyewitnesses
harnesses
likenesses
thicknesses
sicknesses
agribusinesses
lionesses
governesses
canonesses
kindnesses
wildernesses
highnesses
deaconesses
consciousnesses
jeunesses (French?)
eye-witnesses
finesses
sadnesses

**Comment by AzadehSafakish** [comment]
>Looking into a dictionary of frequencies, these are the only plurals in the first 400,000 word forms:

Makes sense. Almost all of them are countable too.
I took a quick look at the previous lists, and I think most of those words can be discarded.
Keeping only the words posted above is probably a safe bet, but it would be good to ensure that any derivatives of those words are included as well: businesses/agribusinesses/ecobusinesses, consciousnesses/pseudo-consciousnesses, etc. (those might not be real words, just made up for sake of example).

**Comment by jaumeortola** [comment]
Most of these words are in the dictionary only with the singular form (NN:U). 
Only words in the short list above have plurals.
