### ISSUE TITLE
Doubts with some variants

### ISSUE THREAD

**Issue by jaumeortola** [languagetool-org/english-pos-dict#20]
I'm not sure how to distribute these forms in the dictionaries.
There are more instances of -able/-eable, -ably/-eably.
```
abridgment|abridgement=noun_UN=us|au,ca,gb,nz,za # check variants!
acknowledgment|acknowledgement=noun_U=all|all # check variants!
adjudgment|adjudgement=noun_UN=all|au,gb,nz,za # check variants!
dislodgment|dislodgement=noun=all|all # check variants!
forejudgment|forejudgement=noun_UN=all|au,gb,nz,za # check variants!
forgivable=JJ=all # variants??
forgivably=RB=all # variants??
forgiveable=JJ=all # variants??
interjudgment|interjudgement=noun_UN=all|au,gb,nz,za # check variants!
judgmentalism|judgementalism=NN:U=all|au,gb,nz,za # check variants!
judgmentally|judgementally=RB=all|au,gb,nz,za # check variants!
judgmental|judgemental=JJ=all|au,gb,nz,za # check variants!
judgment|judgement=noun_UN=all|au,gb,nz,za # check variants!
karat|carat=noun=au,ca,nz,us,za|gb # variants??
lodgment|lodgement=noun_UN=all|all # check variants!
misjudgment|misjudgement=noun=all|au,gb,nz,za # check variants!
nonjudgmental|nonjudgemental=JJ=all|au,gb,nz,za # check variants!
preacknowledgment|preacknowledgement=noun_U=all|all # check variants!
prejudgment|prejudgement=noun_UN=all|au,gb,nz,za # check variants!
reacknowledgment|reacknowledgement=noun_U=all|all # check variants!
resizable|resizeable=JJ=us,ca|gb,au,nz,za # variants??
superacknowledgment|superacknowledgement=noun_U=all|all # check variants!
unforgivable=JJ=all # variants??
unforgiveable=JJ=all # variants??
```

**Comment by evan-defran-lt** [comment]
Hi @jaumeortola, what's the due date/priority for this?

**Comment by jaumeortola** [comment]
As long as there are no serious errors, we can live with it. We would like to start doing some tests in production by the middle of next week.

**Comment by jaumeortola** [comment]
These are all the double forms -able/-eable in the dictionary. 

abridgable/abridgeable
bitable/biteable
borable/boreable
bribable/bribeable
choosable/chooseable
citable/citeable
clonable/cloneable
closable/closeable
confinable/confineable
datable/dateable
drapable/drapeable
drivable/driveable
dyable/dyeable
finable/fineable
forgivable/forgiveable
framable/frameable
hatable/hateable
hirable/hireable
linable/lineable
lovable/loveable
makable/makeable
microwavable/microwaveable
minable/mineable
movable/moveable
movable/moveable
movableness/moveableness
nontradable/nontradeable
overtakable/overtakeable
placable/placeable # these are different words. 
probable/probeable
probable/probeable
raisable/raiseable
ratable/rateable
ratable/rateable
reclosable/recloseable
reusable/reuseable
ridable/rideable
ropable/ropeable
savable/saveable
shakable/shakeable
shapable/shapeable
sharable/shareable
sizable/sizeable
sizableness/sizeableness
slakable/slakeable
statable/stateable
tamable/tameable
tradable/tradeable
tunable/tuneable
undatable/undateable
unforgivable/unforgiveable
unframable/unframeable
unhirable/unhireable
unitable/uniteable
unjudgable/unjudgeable
unlovable/unloveable
unmistakable/unmistakeable
unmovable/unmoveable
unnamable/unnameable
unrufflable/unruffleable
unsavable/unsaveable
unshakable/unshakeable
unshamable/unshameable
unshapable/unshapeable
unslakable/unslakeable
unsmokable/unsmokeable
unstatable/unstateable
untakable/untakeable
untamable/untameable
untastable/untasteable
untradable/untradeable
unusable/unuseable
unwadable/unwadeable
upgradable/upgradeable
usable/useable
votable/voteable
wadable/wadeable
writable/writeable

**Comment by evan-defran-lt** [comment]
I will have time on Friday, 27/6, to take a look.

**Comment by evan-defran-lt** [comment]
I've done my best to assign dialects for -able/-eable words. It is quite messy. There seem to be some general trends, but the truth is that all dialects seem to make use of both variants. I consulted several dictionaries from the dialects + Google's ngram viewer for comparisons and trends. 
The file is in a different format from what's prescribed for the dictionaries, because I think this is slightly more transparent for reviewing, but it would be easy enough to reformat. 
[able_eable_words.csv](https://github.com/user-attachments/files/16067432/able_eable_words.csv)

**Comment by jaumeortola** [comment]
Thank you, @evan-defran-lt! 
I found that `forgiveable` is marked as misspelling in Wiktionary (https://en.wiktionary.org/wiki/forgiveable), and it seems to be missing in many dictionaries. 

Did you check the words in the first comment (abridgment, acknowledgment...)? Do the variants make sense as they are now?

**Comment by evan-defran-lt** [comment]
> I found that forgiveable is marked as misspelling in Wiktionary (https://en.wiktionary.org/wiki/forgiveable), and it seems to be missing in many dictionaries.

Sorry, that was my mistake. It indeed is a misspelling. 

> Did you check the words in the first comment (abridgment, acknowledgment...)? Do the variants make sense as they are now?

I will check those today.

**Comment by evan-defran-lt** [comment]
Had a look for words in the first comment. 

`forgiveable` and `unforgiveable` seem to be errors in all dialects of EN.
from what I've been able to confirm:
```
karat|carat=noun=us|all
```
I've not been able to find `resizeable` attested anywhere (except [Wiktionary](https://en.wiktionary.org/wiki/resizeable), with no references), although by analogy, it should be acceptable in au, ca, gb, nz and za. 

The rest look fine.
