### ISSUE TITLE
changes in the tagger dictionary

### ISSUE THREAD

**Issue by jaumeortola** [languagetool-org/english-pos-dict#3]
- [x] Removed from the tagger. They are useless because they contain a word separator (`/`). They could be added to multiwords.txt or just ignored. https://github.com/languagetool-org/english-pos-dict/commit/fcd9226bbe7b065884a64b9867225380040874aa
```
A/C	A/C	NNP
A/O	A/O	NNP
A/P	A/P	NNP
A/V	A/V	NNP
A/m	A/m	NNP
B/B	B/B	NNP
B/D	B/D	NNP
B/o	B/o	NNP
C/A	C/A	NNP
C/D	C/D	NNP
C/L	C/L	NNP
C/N	C/N	NNP
D/A	D/A	NNP
D/F	D/F	NNP
D/L	D/L	NNP
D/O	D/O	NNP
D/P	D/P	NNP
D/W	D/W	NNP
P/C	P/C	NNP
PL/1	PL/1	NNP
R/D	R/D	NNP
S/D	S/D	NNP
and/or	and/or	CC
b/l	b/l	NN
counts/minute	counts/minute	NN
cycles/second	cycles/second	NN
input/output	input/output	NN
km/h	km/h	NN
m/s	m/s	NN
roll-on/roll-off	roll-on/roll-off	JJ
s/n	s/n	NN
signal/noise	signal/noise	NN
tcp/ip	tcp/ip	NN
w/o	w/o	NN
```

- [x] Removed from the tagger. Just a typo? https://github.com/languagetool-org/english-pos-dict/commit/d5f3570faa36c5e900d5ca1e6140a92d29d2f29e
```
mari,nade	mari,nade	NN
```
- [x] Removed from the tagger. If these tags are needed, they should be introduced in disambiguation.xml.
```
,      ,       ,
.      .       .
```

**Comment by jaumeortola** [comment]
- [x] These tagger entries seem incomplete or wrong. (Format: wordform lemma POStag)
(For the record: these entries were found searching lemmas with only one form, and form != lemma)

```
Caymans Cayman NNPS
Cisalpines Cisalpine NNPS
Judaisers Judaiser NNS
SDKs SDK NNS
SVGs SVG NNS
Vestiaire SVestiaire NNP    [typo?]
abyes abye VBZ
accessors accessor NNS
aero-engines aero-engine NNS
all-girls all-girl JJ
blowses blows NNS
buttonses buttons NNS
califs calif NNS
canonicalisations canonicalisation NNS
canonicalizations canonicalization NNS
carses cars NNS
coinfections coninfection NNS
destigmatizations destigmatization NNS
doits doit NNS
ebicycles ebicycle NNS
ex-communists ex-communist NN
ex-partners ex-partner NNS
ex-students ex-student NNS
fremds fremd NNS
gives gif NNS
idlesses idles NNS
mines minis NNS
non-cooperations non-cooperation NNS
non-ionising non-ionise VBG
numberses numbers NNS
orthogonalisations orthogonalisation NNS
panellisations panellisation NNS
panellizations panellization NNS
pliers plier NNS
preallocations preallocation NNS
reauthorisations reauthorisation NNS
recentralisations recentralisation NNS
reinitialisations reinitialisation NNS
reinitializations reinitialization NNS
resynchronisations resynchronisation NNS
resynchronizations resynchronization NNS
roguelikes roguelike NNS
sayeds sayed NNS
seventeen-year-olds seventeen-year-old NNS
successes succes NNS
tumefying temefy VBG
twenty-year-olds twenty-year-old NNS
unequalising unequalise VBG
uninstallation uninstallations NNS  [form and lemma are swapped!]
wusses wus NNS
```

In most cases, there is a plural form (`resynchronizations`), but no singular form (`resynchronization` is missing in the dictionary).

@AzadehSafakish Make the corrections in this file: https://github.com/languagetool-org/english-pos-dict/blob/main/tagger-dict/english-tagger.txt
Alternatively, I can do a PR for you to review.

**Comment by AzadehSafakish** [comment]
>Removed from the tagger. If these tags are needed, they should be introduced in disambiguation.xml.
,      ,       ,
.      .       .

@jaumeortola Will removing these cause any issues for XML rules that use `postag=","`?
It appears quite frequently in all XML files.

**Comment by jaumeortola** [comment]
>  Will removing these cause any issues for XML rules that use postag=","?

It will cause issues, yes. The simplest solution is to add the tag in a disambiguation rule.
